New Post: Add-plugins, Add-mods
FalixNodes-Software/KB-articles pull request #14
Opened 2024-07-26 19:38 UTC by theTWIXhunter

2024-07-26 21:43 UTC, iamdeka requested changes

2024-07-26 21:43 UTC, iamdeka commented on 2024-07-10-install-mods.md
> +author: The_twix_hunter
`theTWIXhunter` looks better

2024-07-26 21:43 UTC, iamdeka commented on _drafts/minecraft/plugins/2024-07-09-install-plugins.md
> +author: The_twix_hunter
`theTWIXhunter` looks better

2024-07-26 22:20 UTC, iamdeka commented on 2024-07-10-install-mods.md
> +4. Navigate to the [FileManager](https://client.falixnodes.net/server/filemanager?dir=/) by hovering over "Manage" and clicking ["FileManager"](https://client.falixnodes.net/server/filemanager?dir=/)
Please, don't write File Manager like that. Hyperlinks can have spaces.

2024-07-26 22:30 UTC, iamdeka approved these changes

2024-07-26 22:33 UTC, iamdeka commented
You also put the articles in the wrong folders
They should be in `/content/_posts`

2024-07-26 22:36 UTC, iamdeka commented
The dates and file names for linking are also mismatching. Please pay more attention to where you're putting the articles, and how they are named

2024-07-27 06:42 UTC, theTWIXhunter commented on 2024-07-10-install-mods.md
> +author: The_twix_hunter
Oh, I will note (and change) that Will

2024-07-27 06:55 UTC, iamdeka approved these changes

2024-07-27 09:11 UTC, theTWIXhunter commented
wait, I commited the old files again

2024-07-27 09:11 UTC, theTWIXhunter commented
whoeps wrong file

2024-07-27 09:39 UTC, theTWIXhunter commented
ok, recommited your changes

2024-07-27 19:27 UTC, iamdeka requested changes
...

![dGz14o0Q0V](https://github.com/user-attachments/assets/b0ef8d8b-0e90-415a-a083-2da3f34f9c00)

2024-07-27 19:32 UTC, theTWIXhunter commented
eurgg

2024-07-27 19:33 UTC, theTWIXhunter commented
I don't have a mc/java in my main

2024-07-27 19:43 UTC, theTWIXhunter commented
fixed it (hope fullt)

2024-07-27 20:34 UTC, iamdeka commented
> fixed it (hope fullt)

I don't see any commits

2024-07-28 06:04 UTC, theTWIXhunter commented
> I don't see any commits

I committed it

2024-07-28 06:18 UTC, theTWIXhunter commented
Committed is a small word, I committed it 6 times (I moved them to Java/mods and Java/plugins and I renamed them to 2024-07-27 (I made them on 10 that’s why they where called that on my pc)

2024-07-29 04:02 UTC, iamdeka commented
![m0E9xVMdFX](https://github.com/user-attachments/assets/cf701dde-88a2-47df-8dc2-34c6ee524769)

Put them in /content/....

2024-07-29 04:02 UTC, iamdeka requested changes
⬆️

2024-07-29 06:15 UTC, theTWIXhunter commented
looks like they are now in /content/

2024-07-29 08:59 UTC, iamdeka approved these changes

2024-07-30 14:00 UTC, closed without merging

2024-07-30 15:38 UTC, theTWIXhunter commented
I didn't close this

2024-07-31 04:15 UTC, iamdeka commented
> deleted the branch FalixNodes-Software:main

🤦

2024-07-31 04:25 UTC, KuroiJigoku commented
did bro just- deleted the branch that had these stuffs 🤦

2024-07-31 09:38 UTC, theTWIXhunter commented
> did bro just- deleted the branch that had these stuffs 🤦

I messed up some articles between diffrt Branches so I just reuploaded to a new branch