resource-pack update
FalixNodes-Software/KB-articles pull request #16
Opened 2024-07-27 19:11 UTC by tp-duolingo

Fixed some markdown issues and rewrote a tiny amount of it

2024-07-27 20:23 UTC, iamdeka requested changes

2024-07-27 20:23 UTC, iamdeka commented on content/_posts/minecraft/bedrock/2024-07-13-resource-pack.md
> +- This guide will demonstrate how to add a server-wide resource pack popup to allow users to enable and use a specified resource pack, or alternatively, enforce it for all players.
⁉️

2024-07-27 20:23 UTC, iamdeka commented on content/_posts/minecraft/bedrock/2024-07-13-resource-pack.md
> +You can also upload your own custom resource pack too.
⁉️

2024-07-27 20:23 UTC, iamdeka commented on content/_posts/minecraft/bedrock/2024-07-13-resource-pack.md
> +- Download the resource pack.
⁉️

2024-07-27 20:33 UTC, iamdeka approved these changes

2024-07-27 20:48 UTC, tp-duolingo commented on README.md
> +You're currently viewing the source code that makes up the [Knowledge Base](https://kb.falixnodes.net/) of FalixNodes. It's all built on Jekyll, a static website generator we use.
there were unnecessary lines

2024-07-27 20:48 UTC, tp-duolingo commented on content/_posts/minecraft/bedrock/2024-07-13-resource-pack.md
> +- This guide will demonstrate how to add a server-wide resource pack popup to allow users to enable and use a specified resource pack, or alternatively, enforce it for all players.
added a bullet so it looks better

2024-07-27 20:49 UTC, tp-duolingo commented on content/_posts/minecraft/bedrock/2024-07-13-resource-pack.md
> +You can also upload your own custom resource pack too.
why did you comment on this ❔

2024-07-27 20:49 UTC, tp-duolingo commented on content/_posts/minecraft/bedrock/2024-07-13-resource-pack.md
> +- Download the resource pack.
why did you comment on this part 2

2024-07-29 04:06 UTC, iamdeka commented
Make a separate PR for readme edit and for each of the article edits.

2024-07-29 04:06 UTC, closed without merging

2024-07-29 20:01 UTC, tp-duolingo commented
Since when you could edit pr's 🤔 But alright, taken into consideration

2024-07-30 03:09 UTC, iamdeka commented
> Since when you could edit pr's 🤔

Create a different branch in your fork for each pr