New-post: Choosing the Right Minecraft Server Jar
FalixNodes-Software/KB-articles pull request #21
Opened 2024-08-09 00:01 UTC by Lovinoes

I wrote a guide on some popular Minecraft server jars. Minecraft is our beloved game, so feel free to suggest more jars or improvements! The guide provides a complete detailed comparison of options like Pufferfish, Paper, Purpur and so on... 🙂

2024-08-10 15:48 UTC, iamdeka requested changes

2024-08-10 15:48 UTC, iamdeka commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +Mohist is a server jar that combines the capabilities of Forge and Bukkit, allowing for the use of both Forge mods and Bukkit plugins. It’s ideal for servers that need to blend the extensive modding
https://essentialsx.net/do-not-use-mohist.html
https://github.com/EssentialsX/Website/pull/44
https://github.com/EssentialsX/Essentials/pull/3580

2024-08-10 15:48 UTC, iamdeka commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Combining Plugins and Mods**: Consider **Mohist**, **Magma**, **Arclight**, **NeoForge**, or **Quilt** based on your specific needs for modding and plugin compatibility.
👎

2024-08-10 15:48 UTC, iamdeka commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +## Conclusion
I would suggest against promoting the usage of hybrid server software (except SpongeForge, i guess)

2024-08-10 15:48 UTC, iamdeka commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For a Plugin-Only Server**: Choose **SpongeVanilla** if you want to use Sponge plugins without the need for Forge mods, ensuring a streamlined plugin experience.
> For a Plugin-Only Server

⁉️

2024-08-10 15:48 UTC, iamdeka commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Networking Multiple Servers**: Use **BungeeCord** or **Waterfall** for traditional proxy setups, or **Velocity** if you need advanced performance and security features.
BungeeCord is considered legacy and most server administrators should use Velocity or at least Waterfall instead

2024-08-10 15:48 UTC, iamdeka commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Basic Performance and Compatibility**: Use **Spigot** if you need a reliable server with good plugin support.
Spigot doesn't support Paper plugins (duh)

2024-08-10 17:10 UTC, Lovinoes commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Basic Performance and Compatibility**: Use **Spigot** if you need a reliable server with good plugin support.
> Spigot doesn't support Paper plugins (duh)

It doesn't say anywhere that it supports Paper plugins. 99% of plugins out there are built for either Bukkit or Spigot. (duh)

2024-08-10 17:13 UTC, Lovinoes commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Networking Multiple Servers**: Use **BungeeCord** or **Waterfall** for traditional proxy setups, or **Velocity** if you need advanced performance and security features.
> BungeeCord is considered legacy and most server administrators should use Velocity or at least Waterfall instead.

Good point. I'll edit that

2024-08-10 17:21 UTC, iamdeka commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Basic Performance and Compatibility**: Use **Spigot** if you need a reliable server with good plugin support.
"For Basic Performance and **Compatibility**"

2024-08-10 17:37 UTC, Lovinoes commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Basic Performance and Compatibility**: Use **Spigot** if you need a reliable server with good plugin support.
my bad

2024-08-10 17:40 UTC, Lovinoes commented
Adjusted the things with Mohist, Spigot, "Plugin-Only Server", and hybrid servers. I hope it's good now 🤷‍♂️

2024-08-10 21:41 UTC, Lovinoes commented
I'm in the process of reorganizing some things. Please don't merge *if accepted* ^_____^

2024-08-11 13:10 UTC, Lovinoes commented
It's ready imo. You might want to add a few more "warnings" because Idfk how to mark some notes properly.

2024-08-11 13:44 UTC, iamdeka commented
deleted the file i made changes to and made a new one 😄

2024-08-11 13:44 UTC, Lovinoes commented
> deleted the file i made changes to and made a new one 😄

I am gigachad I know

2024-08-11 13:51 UTC, Lovinoes commented on content/_posts/minecraft/java/2024-08-10-choosing-the-right-minecraft-server-jar.md
> +- **For Networking Multiple Servers**: Use **BungeeCord** or **Waterfall** for traditional proxy setups, or **Velocity** if you need advanced performance and security features.
Done

2024-08-21 20:21 UTC, iamdeka commented
Thought you were gonna do it for Bedrock software too, godspeed

2024-08-22 20:51 UTC, Mocab approved these changes

2024-08-23 10:54 UTC, iamdeka approved these changes

2024-08-23 18:53 UTC, merged