New Post: Java Resource Packs
FalixNodes-Software/KB-articles pull request #3
Opened 2024-07-15 04:12 UTC by KuroiJigoku

2024-07-15 11:10 UTC, iamdeka requested changes

2024-07-15 11:10 UTC, iamdeka commented on _posts/minecraft/java/2024-07-13-java-rp.md
> +title:  "Resource Packs"
```diff
- title:  "Resource Packs"
+ title: "How to add a resource pack to your server"
```

2024-07-15 11:10 UTC, iamdeka commented on _posts/minecraft/java/2024-07-13-java-rp.md
> +description: "Uploading Resource Packs into your Java Server"
```diff
- description: "Uploading Resource Packs into your Java Server"
+ description: "How to make your Java server require a Resource Pack"
```

2024-07-15 11:10 UTC, iamdeka commented on _posts/minecraft/java/2024-07-13-java-rp.md
> +## How to Add a Resource Pack to the Minecraft Server
```diff
- ## How to Add a Resource Pack to the Minecraft Server
+ ## Adding a Resource Pack to the server
```

2024-07-15 11:10 UTC, iamdeka commented on _posts/minecraft/java/2024-07-13-java-rp.md
> +1. Upload the resource pack to [Dropbox](https://www.dropbox.com/home) or a similar filesharing service.
Dropbox 🙄

2024-07-15 11:10 UTC, iamdeka commented on _posts/minecraft/java/2024-07-13-java-rp.md
> +8. (re)Start the server
```diff
- 8. (re)Start the server
+ 8. Start or restart the server
```

2024-07-15 11:13 UTC, iamdeka commented on _posts/minecraft/java/2024-07-13-java-rp.md
> +Resource packs are a popular way to customize the visual and auditory aspects of Minecraft Java Edition. Whether you're looking to enhance the game with realistic textures, add thematic elements, or
I smell the AI

2024-07-15 11:21 UTC, KuroiJigoku commented on _posts/minecraft/java/2024-07-13-java-rp.md
> +1. Upload the resource pack to [Dropbox](https://www.dropbox.com/home) or a similar filesharing service.
men...its the easy one out there 🙄

2024-07-16 15:32 UTC, Mocab approved these changes
If anyone has anything else to add lmk

2024-07-16 15:33 UTC, KuroiJigoku commented
Deka approved :D
me got nothin' else to edit on i think :3

2024-07-16 15:35 UTC, merged