New post: Add modpacks
FalixNodes-Software/KB-articles pull request #39
Opened 2024-12-10 18:02 UTC by theTWIXhunter

why didn't we have this earlier

2024-12-10 18:35 UTC, iamdeka requested changes
Majority of the text is about mods, not modpacks

2024-12-10 19:47 UTC, theTWIXhunter commented
IK (I just duplicated the mods article), I don't know what to do with the section on top but everything beneath it should have been changed to modpacks

2024-12-10 21:35 UTC, Lovinoes commented
1. Don't duplicate random articles. (or rename mods to modpacks.)
2. Write your own article (switch to draft PR)

2024-12-30 21:54 UTC, iamdeka requested changes
do you ever proofread

> lorepsum > ipsum > work > in > progress(modrinth downtime) for modrinth.

2025-01-25 12:52 UTC, Mocab approved these changes
crazy how modpack creators can use java but fail at organising a few files

2025-01-30 16:04 UTC, iamdeka approved these changes

2025-01-30 16:59 UTC, merged