New Post: Creating an Extra Port
FalixNodes-Software/KB-articles pull request #9
Opened 2024-07-15 12:03 UTC by Nahokey

2024-07-23 21:12 UTC, Mocab approved these changes

2024-07-24 13:29 UTC, iamdeka requested changes

2024-07-24 13:29 UTC, iamdeka commented on content/_posts/falix/dashboard/2024-07-03-extra-port.md
> +description: Extra ports, sometimes known as forwarded ports, can allow special mods/plugins to deliver content over the port instead of the primary port.
This description is not the best for this article

2024-08-08 16:19 UTC, iamdeka approved these changes

2024-08-16 21:14 UTC, merged